### ISSUE TITLE
CMake failed to find MXML

### ISSUE THREAD

**Issue by clementperon** [ARM-software/gator#37]
Hi,

I'm trying to build gator 8.1.0 but Cmake complain that it can't find MXML
```
| CMake Error at CMakeLists.txt:67 (FIND_PACKAGE):
|   Could not find a package configuration file provided by "mxml" with any of
|   the following names:
| 
|     mxmlConfig.cmake
|     mxml-config.cmake
```
https://github.com/ARM-software/gator/blob/c1e117edddbdd7f9a23528bdf0355e5249abf52c/daemon/CMakeLists.txt#L89

Looking at the mxml library, but it looks like it doesn't support CMake build at the moment :

https://github.com/michaelrsweet/mxml
See: https://github.com/michaelrsweet/mxml/pull/281

**Comment by bengaineyarm** [comment]
Hi @clementperon thanks for this. I guess you are using system provided dependencies, rather than using vcpkg?

Presumably, if you are using your own dependency manager, you can provide mxml with iirc pkg-config configuration, or something like that... I expect we just need an 

if (VCPKG) do x else do y 

construct in the cmake to handle this case.

**Comment by bengaineyarm** [comment]
@clementperon Are you able to let me know if this works for you: https://github.com/ARM-software/gator/pull/39

**Comment by bengaineyarm** [comment]
Resolved by https://github.com/ARM-software/gator/pull/39
